# Generated by Django 4.2.7 on 2023-11-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampusName', models.CharField(blank=True, default='', max_length=60)),
                ('State', models.CharField(blank=True, default='', max_length=2)),
                ('CampusID', models.IntegerField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'University Campuses',
            },
        ),
    ]
